version: '3'
services:

    # سرویس PHP
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: apps/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./../public:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    # سرویس Nginx
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./../public:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    # سرویس MySQL
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"  # اطمینان از تطابق پورت‌ها
        environment:
            MYSQL_DATABASE: crm_db
            MYSQL_ROOT_PASSWORD: 123456
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

# شبکه‌های داکر
networks:
    app-network:
        driver: bridge

# ولوم‌ها
volumes:
    dbdata:
        driver: local
